export     const mevalar = [
  {
    nomi: "Olma",
    narxi: 8000,
    sifati: "Yuqori",
    miqdori: "1 kg",
    kelibChiqishi: "Farg'ona",
    mavsum: "Kuz",
    vitaminlar: ["C", "B1", "B2"],
    sharh: "Shirin va suvli, bolalar uchun foydali",
    chegirmaFoizi: 10,
    img: "./images/apple.png"
  },
  {
    nomi: "Banan",
    narxi: 15000,
    sifati: "O'rta",
    miqdori: "1 kg",
    kelibChiqishi: "Ekvador",
    mavsum: "Yil bo'yi",
    vitaminlar: ["B6", "C", "A"],
    sharh: "Import qilinadi, tez yetiladi",
    chegirmaFoizi: 5,
    img: "./images/banana.png"

  },
  {
    nomi: "Anor",
    narxi: 12000,
    sifati: "Yuqori",
    miqdori: "1 kg",
    kelibChiqishi: "Qandora",
    mavsum: "Kuz-yoz",
    vitaminlar: ["C", "K", "Folat"],
    sharh: "Donalari yirik, yurak faoliyatiga foydali",
    chegirmaFoizi: 15,
    img: "./images/pomegranate.png"
  },
  {
    nomi: "Uzum",
    narxi: 10000,
    sifati: "Yaxshi",
    miqdori: "1 kg",
    kelibChiqishi: "Samarqand",
    mavsum: "Yoz",
    vitaminlar: ["C", "K", "B2"],
    sharh: "Qora uzum, energiya beradi",
    chegirmaFoizi: 0,
    img: "./images/grapes.png",
    shop: "bag-outline",
  },
  {
    nomi: "Nok",
    narxi: 9000,
    sifati: "O'rta",
    miqdori: "1 kg",
    kelibChiqishi: "Namangan",
    mavsum: "Yoz",
    vitaminlar: ["C", "K"],
    sharh: "Teri uchun foydali",
    chegirmaFoizi: 10,
    img: "./images/pear.png"
  },
  // {
  //   nomi: "Shaftoli",
  //   narxi: 11000,
  //   sifati: "Yuqori",
  //   miqdori: "1 kg",
  //   kelibChiqishi: "Andijon",
  //   mavsum: "Yoz",
  //   vitaminlar: ["A", "C", "E"],
  //   sharh: "Shirin va yumshoq, hazm qilishni yaxshilaydi",
  //   chegirmaFoizi: 20,
  //   img: ""
  // },
  // {
  //   nomi: "Gilos",
  //   narxi: 13000,
  //   sifati: "Yuqori",
  //   miqdori: "1 kg",
  //   kelibChiqishi: "Toshkent viloyati",
  //   mavsum: "Bahor-yoz",
  //   vitaminlar: ["C", "A", "K"],
  //   sharh: "Tana uchun antioksidant manbai",
  //   chegirmaFoizi: 10,
  //   img: ""
  // },
  // {
  //   nomi: "Apelsin",
  //   narxi: 14000,
  //   sifati: "Yaxshi",
  //   miqdori: "1 kg",
  //   kelibChiqishi: "Turkiya",
  //   mavsum: "Qish",
  //   vitaminlar: ["C", "B1", "Folat"],
  //   sharh: "Immunitetni kuchaytiradi",
  //   chegirmaFoizi: 5,
  //   img: ""
  // },
  // {
  //   nomi: "Limon",
  //   narxi: 10000,
  //   sifati: "Yuqori",
  //   miqdori: "1 kg",
  //   kelibChiqishi: "Surxondaryo",
  //   mavsum: "Qish-yil bo'yi",
  //   vitaminlar: ["C", "B6"],
  //   sharh: "Grippga qarshi tabiiy dori",
  //   chegirmaFoizi: 10,
  //   img: ""
  // },
  // {
  //   nomi: "Xurmo",
  //   narxi: 9000,
  //   sifati: "O'rta",
  //   miqdori: "1 kg",
  //   kelibChiqishi: "Qashqadaryo",
  //   mavsum: "Kuz",
  //   vitaminlar: ["A", "C", "E"],
  //   sharh: "Temirga boy, qon bosimini me’yorga keltiradi",
  //   chegirmaFoizi: 5,
  //   img: ""
  // }
];
